name: Validate Public Keys

on:
  push:
    paths:
      - 'keys/**'
      - '.github/keys-whitelist.txt'
  pull_request:
    paths:
      - 'keys/**'
      - '.github/keys-whitelist.txt'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate-keys:
    name: Validate Public Keys
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    strategy:
      matrix:
        # Process keys in batches to handle large pushes efficiently
        batch-size: [50]
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Get full history for change detection
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Detect changed keys
      id: changed-files
      uses: dorny/paths-filter@v2
      with:
        filters: |
          keys:
            - 'keys/**'
          whitelist:
            - '.github/keys-whitelist.txt'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography pyopenssl
        
    - name: Validate public keys
      id: validate-keys
      run: |
        python .github/scripts/validate_keys.py \
          --batch-size ${{ matrix.batch-size }} \
          --whitelist .github/keys-whitelist.txt
      env:
        GITHUB_SHA: ${{ github.sha }}
        GITHUB_REF: ${{ github.ref }}
    
    - name: Upload validation report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: key-validation-report
        path: validation-report.json
        retention-days: 7

    - name: Fail if validation errors
      if: steps.validate-keys.outcome == 'failure'
      run: |
        echo "❌ Public key validation failed"
        echo "Check the validation report for details"
        exit 1
