# .github/branch-protection.yml
name: Main branch protection

rules:
  - name: "Main branch protection"
    branches: ["main", "master"]
    protection:
      # Basic protections
      required_status_checks:
        strict: true
        contexts:
          - "Validate Public Keys"
          - "Security Scan"
      
      # Require pull requests
      required_pull_request_reviews:
        required_approving_review_count: 2
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
        require_last_push_approval: true
      
      # Require signed commits
      require_signed_commits: true
      
      # Lock branch
      lock_branch: false
      
      # Restrict who can push
      restrictions:
        apps: []
        users: []
        teams:
          - "security-team"
          - "admins"
      
      # Additional protections
      allow_force_pushes: false
      allow_deletions: false
      required_conversation_resolution: true
      required_linear_history: true
      
      # Require specific workflows to pass
      required_status_checks:
        strict: true
        contexts:
          - "validate-keys"
          - "codeql-analysis"
          - "security-scan"
